---
# Core settings
title: "Angular Development Reference"
description: "Reference documentation for Angular development"
baseurl: "/angular"
url: "https://juparave.github.io"
github_username: juparave

# Theme and display settings
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Navigation settings
header_pages:
  - index.md

# Repository links mapping
repository_links:
  angular: "/angular/"
  cloud: "/cloud/"
  dart: "/dart/"
  flask: "/flask/"
  flutter: "/flutter/"
  git: "/git/"
  golang: "/golang/"
  linux: "/linux/"
  turbogears: "/turbogears/"

# SEO and social plugins
plugins:
  - jekyll-seo-tag

github: true
---